
GET http://localhost:3001/zooanimals 

###

GET http://localhost:3001/zooanimals/64b80a7137182aec23418fca

###

POST http://localhost:3001/zooanimals
Content-Type: application/json

{
    "animaltype": "frog",
    "animalname": "frank"
}

###

DELETE http://localhost:3001/zooanimals/64b8081d87e1d6d03a0e516b

###
PATCH http://localhost:3001/zooanimals/64b807aca0ed0bb69ac39876
Content-Type: application/json

{
    "animalname": "Fiona"

}